BEGIN TRANSACTION;
CREATE TABLE `user` (
	`name`	TEXT,
	`id`	INTEGER,
	`age`	INTEGER
);
INSERT INTO `user` VALUES ('bbb',234,56);
INSERT INTO `user` VALUES ('ccc',222,44);
INSERT INTO `user` VALUES ('aaa',123,34);
COMMIT;
